---

- name: Recursively change ownership of a directory
  become: yes 
  file:
    path: /home/{{ user_name }}
    state: directory
    recurse: yes
    owner: "{{ user_name }}"
    group: "{{ user_name }}"
 