---
- block:

  - name: 'plex : download plex dpkg file'
    shell: wget -c https://downloads.plex.tv/plex-media-server-new/1.19.5.3112-b23ab3896/debian/plexmediaserver_1.19.5.3112-b23ab3896_amd64.deb -O plex.deb
    args:
      chdir: /home/{{ user_name }}
      warn: no 

  - name: 'plex : Install Plex dpkg file'
    become: yes 
    apt:
      deb: /home/{{ user_name }}/plex.deb

  - name: 'plex : run dpkg -L plexmediaserver to enable plex repository'
    become: yes
    shell: sudo dpkg -L plexmediaserver
    register: packages
    args:
      warn: no

  - debug:
      var: packages.stdout

  - name: 'plex : enable sources for plex'
    become: yes 
    lineinfile: 
      dest: /etc/apt/sources.list.d/plexmediaserver.list
      regexp: "^#?deb https://downloads.plex.tv/repo/deb/ public main"
      line: deb https://downloads.plex.tv/repo/deb/ public main

  - name: 'plex : add plex key'
    become: yes 
    apt_key:
      url:  https://downloads.plex.tv/plex-keys/PlexSign.key
      state: present

  - name: 'plex : update system'
    apt:
      update_cache: yes

  - name: 'plex : start plexmediaserver'
    systemd:
      state: started
      name: plexmediaserver  
    
  tags:
    - cloud-torrent
    - plex 