---

- name: Install the `unattended-upgrades` package
  package:
    name: unattended-upgrades
    state: present
  tags: unattended
   
- name: Copy the `50unattended` configuration file
  copy:
    src: ../templates/50unattended-upgrades.j2  
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    force: yes
    owner: root
    group: root
    mode: 0644
  tags: unattended
   
- name: Copy the `20auto-upgrades` configuration file
  copy:
    src: ../templates/20auto-upgrades.j2
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    owner: root
    group: root
    mode: 0644
  tags: unattended