---

- name: Install auditd
  apt:
    name: auditd
    state: present
  
- name: "start auditd"
  systemd:
    name: auditd
    state: started
 
- name: enable service auditd and ensure it is not masked
  systemd:
    name: auditd
    enabled: yes
    masked: no
 
- name: run aditd for for first time
  become: yes
  shell: aureport > auditd-first-run-{{ ansible_date_time.date }}.txt 
  args: 
    chdir: /home/{{ user_name }}/
