---

- name: Install the `fail2ban` package
  package:
    name: fail2ban
    state: latest
  tags: fail2ban
 
- name: Override some basic fail2ban configurations
  copy:
    src: ../templates/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: 0644
  tags: fail2ban
 
- name: Restart fail2ban
  systemd:
    state: restarted
    daemon_reload: yes
    name: fail2ban
  tags: fail2ban 

- name: 'enable fail2ban as a service'
  become: yes 
  systemd:
    name: fail2ban
    enabled: yes 
  tags: fail2ban  
 
